apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-installationaccesstoken-editor-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tokenaut.appthrust.io
  resources:
  - installationaccesstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tokenaut.appthrust.io
  resources:
  - installationaccesstokens/status
  verbs:
  - get