# permissions for end users to edit installationaccesstokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: a
    app.kubernetes.io/managed-by: kustomize
  name: installationaccesstoken-editor-role
rules:
- apiGroups:
  - tokenaut.appthrust.io
  resources:
  - installationaccesstokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tokenaut.appthrust.io
  resources:
  - installationaccesstokens/status
  verbs:
  - get
